language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
env:
  - PORT=58080
install:
  - yarn
script:
  - yarn test
  - yarn build
deploy:
  provider: script
  script: bash ./config/deploy/csc.sh
  on:
    branch: master
