services: docker
script:
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up

deploy:
  provider: script
  script: bash config/docker_push.sh
  on:
    branch: master
