version: '3.7'
services:
  web:
    image: personal-website-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
      - '3001:3001'
