name: Node CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps: 
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - uses: actions/cache@v1
      id: node_modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        
    - name: Install dependencies
      run: yarn
    
    - name: Save
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: .
        
  build:
    needs: [setup]

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    
    steps:
      - name: Download app
        uses: actions/download-artifact@v1
        with:
          name: app

      - name: Build
        run: yarn buid

  test:
    needs: [setup]

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
      - name: Download app
        uses: actions/download-artifact@v1
        with:
          name: app

      - name: Test
        run: yarn test
  
env:
  CI: true
  NODE_ENV: PRODUCTION
